const books = [
  {
    id: 1,
    title: "Clean Code",
    author: "Robert C. Martin",
    price: 29.99,
    category: "Programming",
    stock: 12,
    cover: "/assets/courses/a1.jpg",
    description: "A handbook of agile software craftsmanship.",
    rating: 4.8,
    hours: 10,
  },
  {
    id: 2,
    title: "You Don’t Know JS",
    author: "Kyle Simpson",
    price: 24.99,
    category: "JavaScript",
    stock: 8,
    cover: "/assets/courses/a2.avif",
    description: "Deep dive into JavaScript language and mechanics.",
    rating: 4.6,
    hours: 8,
  },
  {
    id: 3,
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    price: 22.0,
    category: "Programming",
    stock: 15,
    cover: "/assets/courses/a3.avif",
    description: "A modern introduction to programming using JavaScript.",
    rating: 4.5,
    hours: 9,
  },
  {
    id: 4,
    title: "Atomic Habits",
    author: "James Clear",
    price: 18.99,
    category: "Self-Help",
    stock: 20,
    cover: "/assets/courses/a4.avif",
    description: "An easy & proven way to build good habits & break bad ones.",
    rating: 4.9,
    hours: 6,
  },
  {
    id: 5,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt",
    price: 34.99,
    category: "Programming",
    stock: 7,
    cover: "/assets/courses/a5.avif",
    description: "Tips and best practices for effective programming.",
    rating: 4.7,
    hours: 11,
  },
  {
    id: 6,
    title: "Java Script: The Good Parts",
    author: "Douglas Crockford",
    price: 27.5,
    category: "JavaScript",
    stock: 10,
    cover: "/assets/courses/a6.avif",
    description: "A deep dive into the best features of JavaScript.",
    rating: 4.3,
    hours: 7,
  },
  {
    id: 7,
    title: "Design Patterns",
    author: "Erich Gamma",
    price: 39.99,
    category: "Programming",
    stock: 5,
    cover: "/assets/courses/a7.avif",
    description: "Elements of reusable object-oriented software.",
    rating: 4.6,
    hours: 12,
  },
  {
    id: 8,
    title: "Deep Work",
    author: "Cal Newport",
    price: 16.99,
    category: "Productivity",
    stock: 13,
    cover: "/assets/courses/a8.avif",
    description: "Rules for focused success in a distracted world.",
    rating: 4.4,
    hours: 5,
  },
  {
    id: 9,
    title: "Cracking the Coding Interview",
    author: "Gayle Laakmann McDowell",
    price: 35.0,
    category: "Interview Prep",
    stock: 18,
    cover: "/assets/courses/a9.avif",
    description: "189 programming questions and solutions.",
    rating: 4.8,
    hours: 14,
  },
  {
    id: 10,
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    price: 89.99,
    category: "Computer Science",
    stock: 4,
    cover: "/assets/courses/a10.avif",
    description: "Comprehensive book on algorithms.",
    rating: 4.7,
    hours: 20,
  },
];

const courses = [
  {
    id: 101,
    title: "React for Beginners",
    instructor: "Jane Doe",
    author: "Jane Doe",
    price: 99.99,
    category: "Web Development",
    duration: "8 weeks",
    image: "/assets/courses/a11.avif",
    description: "Learn React fundamentals and build interactive UIs.",
    rating: 4.6,
    hours: 30,
  },
  {
    id: 102,
    title: "Advanced JavaScript",
    instructor: "John Smith",
    author: "John Smith",
    price: 149.99,
    category: "Programming",
    duration: "6 weeks",
    image: "/assets/courses/a4.avif",
    description: "Deep dive into advanced JavaScript concepts and patterns.",
    rating: 4.7,
    hours: 25,
  },
  {
    id: 103,
    title: "UI/UX Design Basics",
    instructor: "Emily Johnson",
    author: "Emily Johnson",
    price: 79.99,
    category: "Design",
    duration: "4 weeks",
    image: "/assets/courses/a9.avif",
    description: "Learn the fundamentals of user interface and experience design.",
    rating: 4.3,
    hours: 18,
  },
  {
    id: 104,
    title: "Data Structures & Algorithms",
    instructor: "Michael Lee",
    author: "Michael Lee",
    price: 129.99,
    category: "Computer Science",
    duration: "10 weeks",
    image: "/assets/courses/a2.avif",
    description: "Master data structures and algorithms for coding interviews.",
    rating: 4.8,
    hours: 35,
  },
  {
    id: 105,
    title: "Fullstack Web Development",
    instructor: "Sarah Parker",
    author: "Sarah Parker",
    price: 199.99,
    category: "Web Development",
    duration: "12 weeks",
    image: "/assets/courses/a9.avif",
    description: "Become a fullstack developer with hands-on projects.",
    rating: 4.9,
    hours: 40,
  },
  {
    id: 106,
    title: "Machine Learning 101",
    instructor: "Alan Turing",
    author: "Alan Turing",
    price: 159.99,
    category: "Data Science",
    duration: "8 weeks",
    image: "/assets/courses/a2.avif",
    description: "Introductory course on machine learning concepts and techniques.",
    rating: 4.5,
    hours: 32,
  },
  {
    id: 107,
    title: "Python for Data Science",
    instructor: "Grace Hopper",
    author: "Grace Hopper",
    price: 139.99,
    category: "Programming",
    duration: "7 weeks",
    image: "/assets/courses/a4.avif",
    description: "Learn Python with a focus on data science applications.",
    rating: 4.6,
    hours: 28,
  },
  {
    id: 108,
    title: "Cybersecurity Fundamentals",
    instructor: "Ellen Ripley",
    author: "Ellen Ripley",
    price: 109.99,
    category: "Security",
    duration: "6 weeks",
    image: "/assets/courses/a5.avif",
    description: "Understand the basics of cybersecurity and threat prevention.",
    rating: 4.4,
    hours: 20,
  },
  {
    id: 109,
    title: "Cloud Computing Essentials",
    instructor: "Mark Zuckerberg",
    author: "Mark Zuckerberg",
    price: 119.99,
    category: "Cloud",
    duration: "5 weeks",
    image: "/assets/courses/a7.avif",
    description: "Introduction to cloud services and architecture.",
    rating: 4.2,
    hours: 22,
  },
  {
    id: 110,
    title: "Mobile App Development",
    instructor: "Lisa Ray",
    author: "Lisa Ray",
    price: 129.99,
    category: "Mobile Development",
    duration: "8 weeks",
    image: "/assets/courses/a6.avif",
    description: "Build native and cross-platform mobile applications.",
    rating: 4.5,
    hours: 26,
  },
];
export { books, courses };
